name: GitHubPages

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    name: 编译打包与部署
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm v8
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Project Node_modules
        run: |
          pnpm i

      - name: Build Project
        run: |
          npm run build
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
